### ISSUE TITLE
Incompatability with Hardcore Revival causes all armor to fully break on death

### ISSUE THREAD

**Issue by Arsoth** [CDXX710/kineticyeet-1.21_fabric#1]
Steps to reproduce:
1. Install [Hardcore Revival](https://modrinth.com/mod/hardcore-revival) and [KineticYeet](https://modrinth.com/mod/cdxx-kineticyeet) (1.2.0)
![image](https://github.com/user-attachments/assets/f49b3608-9333-4e80-8b40-827ddcf3e102)
2. Die wearing armor
3. You hear the sound of armor breaking and all your armor is now missing from the loot pile. Grave mods such as [You're in Grave Danger](https://modrinth.com/mod/yigd) and [Universal Graves](https://modrinth.com/mod/universal-graves) do not retain the armor either. This even occurs with the [What Durability](https://modrinth.com/mod/what-durability) mod, which removes all durability from items.

I'm cross posting this to both mod authors repos ([HCR bug report](https://github.com/TwelveIterationMods/HardcoreRevival/issues/145), [KY bug report](https://github.com/CDXX710/kineticyeet-1.21_fabric/issues/1)); I can't even begin to figure out what's causing this and it's only because I know about binary searches I was able to narrow it down to these two.

**Comment by CDXX710** [comment]
KineticYeet is really a simple mod. Its job is literally to yeet ElytraCollision out of the damage types list responsible of bypassing armor.

As fixing this specific issue would require me to rethink the whole code and eventually create many more incompatibilities with other mods, I now suppose this fix will need to be worked on HardcoreRevival's side
